### ISSUE TITLE
Aws lamda

### ISSUE THREAD

**Issue by rajadileepkolli** [rajadilipkolli/aws-stack#180]
https://apurvsheth.medium.com/serverless-with-spring-boot-aws-lambda-bc76c1de2b12

https://betterprogramming.pub/going-serverless-with-spring-cloud-function-aws-lambda-java-17-support-and-snapstart-d3d8ffd44bbd

**Comment by rajadilipkolli** [comment]
https://hashnode.localstack.cloud/cloud-integration-testing-made-easy-localstack-testcontainers#heading-prerequisites
